import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/customs/Navbar";
import SocialMedia from "@/components/customs/SocialMedia";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "h-[100svh] relative flex flex-col w-full dark theme-green max-w-[2100px] mx-auto overflow-hidden"
        )}
      >
        {/* <MousepointerBG /> */}



        <div id="main-navigaionbar" className="top-0 bg-background sticky z-10">
          <div className="flex items-center justify-between w-[90%] mx-auto">
            <div className="text-[1.8rem] text-primary/85 font-bold uppercase tracking-[.2rem]">Florvin</div>
            <SocialMedia />
          </div>
        </div>
        {/* {children} */}
        <div className="overflow-auto flex-1 flex flex-col">{children}</div>

        <div className="sticky max-lg:bottom-0 max-lg:bg-background lg:fixed lg:right-[1rem] lg:top-1/2 lg:-translate-y-1/2 mt-auto">
          <Navbar />
        </div>
      </body>
    </html>
  );
}
